platform :ios, '9.0'

use_frameworks!

pod 'Bindable/UIKit', :path => '../'
# pod 'Bindable', :git => 'git@github.com:Q42/Bindable.git'

target 'Test'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end

